Require the DB model before monkeypatching
Because we define Location here, if the DB model isn’t explicitly required, Rails finds the constant defined and will never load the model itself.  This leads to really confusing messages like “NoMethodError: undefined method `cluster' for #<Location:0x000001085feb88>” when Location very well has a cluster association.